FORMAT: 1A

# Dart-App

DartApp API is a a RESTful API.

There are four main endpoints:

- **Throw**: This is a throw made. A throw is related to a game (which the throw
  belongs to) and a user (who throw the dart).
- **GameType**: Different gametypes such as "20 to 15" or "201".
- **Game**: A single match. A game has a gametype.
- **User**: A person who participates in a game and throw darts.

When making requests, the following headers should be set:
- Accept: application/json
- Content-Type: application/json

## Sorting and Pagination
For some routes the order can be sorted in reverse order by using a query parameter:

### Sorting
- GET ´http://localhost:8000/api/v1/throws?sort_by=asc´
- GET ´http://localhost:8000/api/v1/games?sort_by=asc´

### Pagination
Pagination is used for enpoints where the data is large.
Add query parameter page like so:

- GET ´http://localhost:8000/api/v1/throws?page=2´

# Group Throws

Resources related to throws in the API.

## Throw [/throws/{throw_id}]

+ Parameters
    + throw_id: 1 (required, number) - Id of the throw in form of an integer

### View a Single Throw [GET]

Fetch the details of a single throw using this action.

+ Response 200 (application/json)

        {
            "data": {
                "id": 1,
                "pie_value": 3,
                "multiplier": 2,
                "created_at": "2018-03-14 15:46:43",
                "created_at_human": "3 weeks ago",
                "user": {
                    "data": {
                        "id": 3,
                        "name": "Mac the not so klein",
                        "username": "mcklein",
                        "avatar": "https:\/\/www.gravatar.com\/avatar\/cea373ce39b8332ce5db287c3aa27b5a?s=80&d=retro",
                        "account_type": "admin"
                    }
                },
                "game": {
                    "data": {
                        "id": 11,
                        "created_at": "2018-03-14 15:46:43",
                        "created_at_human": "3 weeks ago",
                        "gametype": {
                            "data": {
                                "id": 1,
                                "name": "20 to 15",
                                "description": "Mollitia est voluptatem animi tempore."
                            }
                        }
                    }
                }
            }
        }

### Update a Single Throw [PATCH]

Update a single throw using this action. It takes a JSON object containing the details of a throw.

+ user_id (number) - Id of the user who made the throw
+ game_id (number) - Id of the game this throw was made in
+ pie_value (number) - Value the dart landed at.
+ multiplier (number) - Multiplier the dart landed at.

+ Request (application/json)

            {
                "user_id": "3",
                "game_id": "2",
                "pie_value": "50",
                "multiplier": "1"
            }

+ Response 200 (application/json)

        {
            "data": {
                "id": 11,
                "pie_value": 50,
                "multiplier": 1,
                "created_at": "2018-03-14 15:46:43",
                "created_at_human": "5 minutes ago",
                "user": {
                    "data": {
                        "id": 3,
                        "name": "Mac Klein",
                        "username": "ali.brakus",
                        "avatar": "https:\/\/www.gravatar.com\/avatar\/cea373ce39b8332ce5db287c3aa27b5a?s=80&d=retro",
                        "account_type": "admin"
                    }
                },
                "game": {
                    "data": {
                        "id": 2,
                        "created_at": "2018-03-14 15:46:43",
                        "created_at_human": "5 minutes ago",
                        "gametype": {
                            "data": {
                                "id": 2,
                                "name": "201",
                                "description": "Repellendus aliquam animi tenetur qui et quam."
                            }
                        }
                    }
                }
            }
        }

### Delete Throw [DELETE]

+ Response 204

## Throws Collection [/throws]

### List All Throws [GET]
List all throws using this action.

+ Response 200 (application/json)

        {
            "data": [{
                "id": 39,
                "pie_value": 1,
                "multiplier": 1,
                "created_at": "2018-04-07 19:10:24",
                "created_at_human": "7 seconds ago",
                "user": {
                    "data": {
                        "id": 1,
                        "name": "Isac Hammes The Second",
                        "username": "isaac",
                        "avatar": "https:\/\/www.gravatar.com\/avatar\/0d1e761d0882962f66ab3abb44130f80?s=80&d=retro",
                        "account_type": "user"
                    }
                },
                "game": {
                    "data": {
                        "id": 20,
                        "created_at": "2018-03-14 15:46:43",
                        "created_at_human": "3 weeks ago",
                        "gametype": {
                            "data": {
                                "id": 1,
                                "name": "20 to 15",
                                "description": "Mollitia est voluptatem animi tempore."
                            }
                        }
                    }
                }
            }, {
                "id": 1,
                "pie_value": 3,
                "multiplier": 2,
                "created_at": "2018-03-14 15:46:43",
                "created_at_human": "3 weeks ago",
                "user": {
                    "data": {
                        "id": 3,
                        "name": "Mac the not so klein",
                        "username": "mcklein",
                        "avatar": "https:\/\/www.gravatar.com\/avatar\/cea373ce39b8332ce5db287c3aa27b5a?s=80&d=retro",
                        "account_type": "admin"
                    }
                },
                "game": {
                    "data": {
                        "id": 11,
                        "created_at": "2018-03-14 15:46:43",
                        "created_at_human": "3 weeks ago",
                        "gametype": {
                            "data": {
                                "id": 1,
                                "name": "20 to 15",
                                "description": "Mollitia est voluptatem animi tempore."
                            }
                        }
                    }
                }
            }]
        }

### Create a New Throw [POST]

You can create new throws using this action.
Note that if the user threw a value of 60, the pie_value should be 20 and the multiplier should be 3.
Moreover, bullseye is represented as 50 with a multiplier of 1.


+ user_id (number) - Id of the user who made the throw
+ game_id (number) - Id of the game this throw was made in
+ pie_value (number) - Value the dart landed at.
+ multiplier (number) - Multiplier the dart landed at.

+ Request Create Single Throw (application/json)

            {
                "user_id": "1",
                "game_id": "20",
                "pie_value": "1",
                "multiplier": "1"
            }

+ Response 200 (application/json)

    + Attributes
        - data (Throw)

+ Request Create Multiple Throws (application/json)

            [
                {
                    "user_id": "1",
                    "game_id": "20",
                    "pie_value": "1",
                    "multiplier": "1"
                },
                {
                    "user_id": "1",
                    "game_id": "20",
                    "pie_value": "2",
                    "multiplier": "1"
                },
                {
                    "user_id": "1",
                    "game_id": "20",
                    "pie_value": "25",
                    "multiplier": "1"
                },
                {
                    "user_id": "3",
                    "game_id": "20",
                    "pie_value": "50",
                    "multiplier": "1"
                }
            ]

+ Response 200 (application/json)

    + Attributes
        - data (array[Throw])

### Update Multiple Throws [PATCH]

You can update multiple throws using this action.
Note that if the user threw a value of 60, the pie_value should be 20 and the multiplier should be 3.
Moreover, bullseye is represented as 50 with a multiplier of 1.


+ id (number) - Id of the throw that should be updated.
+ user_id (number) - Id of the user who made the throw.
+ game_id (number) - Id of the game this throw was made in.
+ pie_value (number) - Value the dart landed at.
+ multiplier (number) - Multiplier the dart landed at.

+ Request (application/json)

            [
                {
                    "id": "11",
                    "user_id": 2
                },
                {
                    "id": "21",
                    "user_id": "3"
                }
            ]

+ Response 200 (application/json)
    + Attributes
        - data (array[Throw])

# Group GameTypes

Resources related to game types in the API.

## GameType [/gametypes/{gametype_id}]

+ Parameters
    + gametype_id: 1 (required, number) - Id of the gametype in form of an integer.

### View a Single GameType [GET]

Fetch the details of a single gametype using this action.

+ Response 200 (application/json)
    + Attributes
        - data (GameType Full)

### Update a Single GameType [PATCH]

Update a single game type using this action. It takes a JSON object containing the details of a gametype.

+ description (string) - Description of the gametype.
+ name (string) - Name of the gametype.

+ Request (application/json)
    + Attributes (GameType NoId)

+ Response 200 (application/json)
    + Attributes
        - data (GameType Full)

### Delete GameType [DELETE]

+ Response 204

## GameTypes Collection [/gametypes]

### List All GameTypes [GET]
List all gametypes using this action.

+ Response 200 (application/json)
    + Attributes
        - data (array[GameType Full])

### Create a New GameType [POST]
Create new gametypes using this action.

+ description (string) - Description of the gametype.
+ name (string) - Name of the gametype.

+ Request Create Single GameType (application/json)
    + Attributes (GameType NoId)

+ Response 200 (application/json)
    + Attributes
        - data (GameType Full)

+ Request Create Multiple GameTypes (application/json)
    + Attributes (array[GameType NoId])

+ Response 200 (application/json)
    + Attributes
        - data (array[GameType Full])

# Data Structures

## Throw (object)

- id: `21` (number) - The unique ID of the throw.
- pie_value: `9` (number) - The pie value of the throw.
- multiplier: `2` (number) - The multiplier of the throw.
- created_at: `2018-03-14 15:46:43` (string) - Date and time when the throw was created.
- created_at_human: `3 weeks ago` (string) - Date and time when the throw was created in human friendly format.

## GameType Full (object)
- id: `21` (number) - The unique ID of the gametype.
- Include GameType NoId

## GameType NoId (object)
- name: `201` (string) - The unique name of the gametype.
- description: `Curabitur et neque quam. Fusce consectetur risus ac consectetur lobortis.` (string) - Description of the gametype.
